config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "ask" => "questions#ask"
  get "answer" => "questions#answer"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    if params[:aQuestion] === "I am going to work"
      @theAnswer = "Great!"
    elsif params[:aQuestion].include? "?"
      @theAnswer = "Silly question, get dressed and go to work!"
    else
      @theAnswer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="main container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="mt-5 the-answer-box">
  <h3><%= params[:aQuestion] %></h3>
  <p class="fst-italic">- You</p>
</div>

<div class="mt-3 the-answer-box-yellow">
  <h3><%= @theAnswer %></h3>
  <p class="fst-italic">- Coach</p>
</div>

<%= link_to "Ask another question", ask_path, { :class => "text-decoration-none"} %>

app/views/questions/ask.html.erb
<h1 class="mt-5">Stupid Coaching</h1>
<p>Ask your coach anything:</p>

<form class="w-50 d-flex" action="/answer" data-turbo="false">
  <input class="form-control" type="text" name="aQuestion">
  <input class="btn btn-primary" type="submit" value="Ask!">
</form>